# Generated by Django 5.0.2 on 2024-02-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
